# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: false
python:
  - 3.6
  - 2.7
cache: pip
install:
  - pip install -r requirements.txt
  - python setup.py install
script: true
