 name: python3-awips
 channels:
   - https://conda.anaconda.org/conda-forge
 dependencies:
   - python=3.6
   - numpy
   - matplotlib
   - cartopy
   - jupyter
   - metpy
   - pint
   - h5py
   - shapely
   - six
   - sphinx>=1.3
   - sphinx_rtd_theme
   - nbconvert>=4.1
   - pip
